"""Genre table

Revision ID: 49a0c4ac8d9c
Revises: c2b4de3028e4
Create Date: 2023-10-22 17:05:42.705638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a0c4ac8d9c'
down_revision: Union[str, None] = 'c2b4de3028e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
