"""Genre table

Revision ID: b172902710a9
Revises: ba5c7b79b342
Create Date: 2023-10-22 17:02:51.318797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b172902710a9'
down_revision: Union[str, None] = 'ba5c7b79b342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('book_authors_book_id_fkey', 'book_authors', type_='foreignkey')
    op.create_foreign_key(None, 'book_authors', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book_authors', type_='foreignkey')
    op.create_foreign_key('book_authors_book_id_fkey', 'book_authors', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###
